name: Build Docker Image for a Single App

on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string

jobs:
  build-docker-image:
    name: Build Docker Image for ${{ inputs.app-dir }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image for ${{ inputs.app-dir }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.app-dir }}:latest docker/${{ inputs.app-dir }}

      # Step 4: Push the Docker image
      - name: Push Docker Image for ${{ inputs.app-dir }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.app-dir }}:latest