name: Docker
on:
  # Trigger the workflow only if changes are detected in either directory
  push:
    paths:
      - 'docker/containerize-backend-app/**' # Monitor changes in the backend directory
      - 'docker/frontend/**'                # Monitor changes in the frontend directory

jobs:
  build-backend-image:
    name: Build Docker Image for Backend
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'docker/containerize-backend-app')

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image for the backend
      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/containerize-backend-app:latest docker/containerize-backend-app

      # Step 4: Push the Docker image for the backend to DockerHub
      - name: Push Backend Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/containerize-backend-app:latest

  build-frontend-image:
    name: Build Docker Image for Frontend
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'docker/frontend')

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image for the frontend
      - name: Build Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest docker/frontend

      # Step 4: Push the Docker image for the frontend to DockerHub
      - name: Push Frontend Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest