name: Trigger Builds for Changed Apps

on:
  push:
    paths:
      - 'docker/**'

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.detect.outputs.changed_dirs }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full commit history

      # Step 2: Detect changed directories
      - name: Detect Changed Directories
        id: detect
        run: |
          # Ensure we have the full commit history
          git fetch --unshallow || true

          # Find directories under 'docker/' with changed files
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | grep '^docker/' | cut -d'/' -f2 | sort | uniq)
          echo "Changed directories: $CHANGED_DIRS"

          # Save the output in an environment file
          echo "changed_dirs=$(echo "[\"$(echo $CHANGED_DIRS | tr ' ' '\",\"')\"]")" >> $GITHUB_ENV

  build-changed-apps:
    name: Build Changed Apps
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-dir: ${{ fromJson(needs.detect-changes.outputs.changed_dirs) }}
      fail-fast: false

    steps:
      # Step 1: Trigger reusable workflow for each changed app
      - name: Call Reusable Workflow
        uses: ./.github/workflows/build-app.yml
        with:
          app-dir: ${{ matrix.app-dir }}